export const FETCH_POPULAR_MOVIES_REQUEST = 'FETCH_POPULAR_MOVIES_REQUEST';
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS';
export const FETCH_POPULAR_MOVIES_ERROR = 'FETCH_POPULAR_MOVIES_ERROR';

export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR';

export const FETCH_MOVIE_RECOMMENDATIONS_REQUEST =
  'FETCH_MOVIE_RECOMMENDATIONS_REQUEST';
export const FETCH_MOVIE_RECOMMENDATIONS_SUCCESS =
  'FETCH_MOVIE_RECOMMENDATIONS_SUCCESS';
export const FETCH_MOVIE_RECOMMENDATIONS_ERROR =
  'FETCH_MOVIE_RECOMMENDATIONS_ERROR';

export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export const FETCH_GENRES_ERROR = 'FETCH_GENRES_ERROR';

export const FETCH_MOVIE_CREDITS_REQUEST = 'FETCH_MOVIE_CREDITS_REQUEST';
export const FETCH_MOVIE_CREDITS_SUCCESS = 'FETCH_MOVIE_CREDITS_SUCCESS';
export const FETCH_MOVIE_CREDITS_ERROR = 'FETCH_MOVIE_CREDITS_ERROR';

export const FETCH_PERSON_REQUEST = 'FETCH_PERSON_REQUEST';
export const FETCH_PERSON_SUCCESS = 'FETCH_PERSON_SUCCESS';
export const FETCH_PERSON_ERROR = 'FETCH_PERSON_ERROR';

export const FETCH_PERSON_MOVIE_CREDITS_REQUEST =
  'FETCH_PERSON_MOVIE_CREDITS_REQUEST';
export const FETCH_PERSON_MOVIE_CREDITS_SUCCESS =
  'FETCH_PERSON_MOVIE_CREDITS_SUCCESS';
export const FETCH_PERSON_MOVIE_CREDITS_ERROR =
  'FETCH_PERSON_MOVIE_CREDITS_ERROR';

export const FETCH_POPULAR_PEOPLE_REQUEST = 'FETCH_POPULAR_PEOPLE_REQUEST';
export const FETCH_POPULAR_PEOPLE_SUCCESS = 'FETCH_POPULAR_PEOPLE_SUCCESS';
export const FETCH_POPULAR_PEOPLE_ERROR = 'FETCH_POPULAR_PEOPLE_ERROR';

export const FETCH_MOVIE_VIDEOS_REQUEST = 'FETCH_MOVIE_VIDEOS_REQUEST';
export const FETCH_MOVIE_VIDEOS_SUCCESS = 'FETCH_MOVIE_VIDEOS_SUCCESS';
export const FETCH_MOVIE_VIDEOS_ERROR = 'FETCH_MOVIE_VIDEOS_ERROR';

export const FETCH_MOVIE_SEARCH_REQUEST = 'FETCH_MOVIE_SEARCH_REQUEST';
export const FETCH_MOVIE_SEARCH_SUCCESS = 'FETCH_MOVIE_SEARCH_SUCCESS';
export const FETCH_MOVIE_SEARCH_ERROR = 'FETCH_MOVIE_SEARCH_ERROR';

export const FETCH_PERSON_SEARCH_REQUEST = 'FETCH_PERSON_SEARCH_REQUEST';
export const FETCH_PERSON_SEARCH_SUCCESS = 'FETCH_PERSON_SEARCH_SUCCESS';
export const FETCH_PERSON_SEARCH_ERROR = 'FETCH_PERSON_SEARCH_ERROR';

export const FETCH_MOVIE_IMAGES_REQUEST = 'FETCH_MOVIE_IMAGES_REQUEST';
export const FETCH_MOVIE_IMAGES_SUCCESS = 'FETCH_MOVIE_IMAGES_SUCCESS';
export const FETCH_MOVIE_IMAGES_ERROR = 'FETCH_MOVIE_IMAGES_ERROR';

export const RESET_POPULAR_MOVIES = 'RESET_POPULAR_MOVIES';
export const RESET_POPULAR_PEOPLE = 'RESET_POPULAR_PEOPLE';
